// backfill_fdw.mjs — parse src/App.jsx raw constants and emit fdw_backfill.sql
// Run:  node scripts/backfill_fdw.mjs
// Output: supabase/migrations/fdw_backfill.sql  (run AFTER fdw_data_warehouse.sql)
//
// Covers the CPM vertical slice (Fleet Overview / CPM Calculator / Driver Detail):
//   fdw_entity (seed) · fdw_period · fdw_driver · fdw_payroll_snapshot ·
//   fdw_fleet_metrics · fdw_efs_statement + fdw_fuel_txn (opening backfill).
// Income / office / contractors / ATL-OTR / trucks follow the same pattern (1b).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, '..', 'src', 'App.jsx');
const OUT = join(__dirname, '..', 'supabase', 'migrations', 'fdw_backfill.sql');
const src = readFileSync(SRC, 'utf8');

// ── literal extraction ────────────────────────────────────────────────────
// Find `let|const NAME =` then bracket-match the following [..] or {..},
// skipping strings and comments so brackets inside them don't miscount.
function extractLiteral(name) {
  const decl = new RegExp(`(?:let|const)\\s+${name}\\s*=\\s*`).exec(src);
  if (!decl) throw new Error(`literal ${name} not found`);
  let i = decl.index + decl[0].length;
  const open = src[i];
  if (open !== '[' && open !== '{') throw new Error(`${name} is not an object/array literal`);
  const close = open === '[' ? ']' : '}';
  let depth = 0, inStr = false, q = '', line = false, block = false;
  const start = i;
  for (; i < src.length; i++) {
    const c = src[i], n = src[i + 1];
    if (line) { if (c === '\n') line = false; continue; }
    if (block) { if (c === '*' && n === '/') { block = false; i++; } continue; }
    if (inStr) { if (c === '\\') { i++; continue; } if (c === q) inStr = false; continue; }
    if (c === '/' && n === '/') { line = true; i++; continue; }
    if (c === '/' && n === '*') { block = true; i++; continue; }
    if (c === '"' || c === "'" || c === '`') { inStr = true; q = c; continue; }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) { i++; break; } }
  }
  const text = src.slice(start, i);
  // eslint-disable-next-line no-eval
  return (0, eval)('(' + text + ')');
}

function scalar(name) {
  const m = new RegExp(`(?:let|const)\\s+${name}\\s*=\\s*([0-9][0-9_.eE+-]*)`).exec(src);
  if (!m) throw new Error(`scalar ${name} not found`);
  return Number(m[1]);
}
function strConst(name) {
  const m = new RegExp(`(?:let|const)\\s+${name}\\s*=\\s*"([^"]*)"`).exec(src);
  if (!m) throw new Error(`string ${name} not found`);
  return m[1];
}

// ── SQL helpers ───────────────────────────────────────────────────────────
const q = v => v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const num = v => v === null || v === undefined || Number.isNaN(v) ? 'null' : String(v);

// ── pull values ───────────────────────────────────────────────────────────
const PAYROLL = extractLiteral('PAYROLL');
const FUEL    = extractLiteral('FUEL');
const PERIOD  = strConst('PERIOD');            // "Jan 1 - Jul 5, 2026"
const sc = Object.fromEntries(['LABOR','FUEL_TOT','GALLONS','MILES','TRUCK_COUNT','TOTAL_HRS',
  'INS_WEEK','INS_TOT','TRUCK_TOT','TRAILER_TOT','TRUCK_MAINT','TRAIL_MAINT','STORAGE',
  'UNIFORMS','FLEET_LOCAL','FLEET_REGIONAL'].map(n => [n, scalar(n)]));

// PERIOD → dates
const pm = PERIOD.match(/(\w+ \d+).*?(\w+ \d+),\s*(\d{4})/);
const yr = pm[3];
const periodStart = '2026-01-01';
const periodEnd = new Date(`${pm[2]}, ${yr}`).toISOString().slice(0, 10);

// ── emit ──────────────────────────────────────────────────────────────────
const L = [];
L.push('-- fdw_backfill.sql — generated by scripts/backfill_fdw.mjs');
L.push(`-- Source: src/App.jsx  PERIOD="${PERIOD}"  (period_end ${periodEnd})`);
L.push('-- Run AFTER fdw_data_warehouse.sql. Idempotent via ON CONFLICT upserts.');
L.push('begin;');

L.push('\n-- entities');
const ents = [['ce','Capacity Express','legal'],['sf','Show Freight','legal'],
  ['ce_east','CE East','legal'],['ja','J&A Management','legal'],
  ['atl','Atlanta Ops','operation'],['otr','OTR Ops','operation']];
for (const [id,label,kind] of ents)
  L.push(`insert into fdw_entity(id,label,kind) values(${q(id)},${q(label)},${q(kind)}) on conflict(id) do nothing;`);

L.push('\n-- period');
L.push(`insert into fdw_period(period_end,period_start,is_current) values(${q(periodEnd)},${q(periodStart)},true) on conflict(period_end) do update set is_current=true;`);

L.push('\n-- drivers (fleet) + payroll snapshot');
for (const p of PAYROLL) {
  const active = p.active === false ? 'false' : 'true';
  L.push(`insert into fdw_driver(name,kind,entity_id,active) values(${q(p.name)},'fleet','sf',${active}) on conflict(name) do update set active=excluded.active;`);
}
for (const p of PAYROLL) {
  const active = p.active === false ? 'false' : 'true';
  L.push(`insert into fdw_payroll_snapshot(driver_id,period_end,hours,total_cost,active) select id,${q(periodEnd)},${num(p.hours)},${num(p.totalCost)},${active} from fdw_driver where name=${q(p.name)} on conflict(driver_id,period_end) do update set hours=excluded.hours,total_cost=excluded.total_cost,active=excluded.active;`);
}

L.push('\n-- fleet metrics (entity sf)');
L.push(`insert into fdw_fleet_metrics(entity_id,period_end,labor,fuel_tot,gallons,miles,fleet_local,fleet_regional,truck_count,total_hrs,ins_tot,truck_tot,trailer_tot,truck_maint,trail_maint,storage,uniforms,ins_week) values('sf',${q(periodEnd)},${num(sc.LABOR)},${num(sc.FUEL_TOT)},${num(sc.GALLONS)},${num(sc.MILES)},${num(sc.FLEET_LOCAL)},${num(sc.FLEET_REGIONAL)},${num(sc.TRUCK_COUNT)},${num(sc.TOTAL_HRS)},${num(sc.INS_TOT)},${num(sc.TRUCK_TOT)},${num(sc.TRAILER_TOT)},${num(sc.TRUCK_MAINT)},${num(sc.TRAIL_MAINT)},${num(sc.STORAGE)},${num(sc.UNIFORMS)},${num(sc.INS_WEEK)}) on conflict(entity_id,period_end) do update set labor=excluded.labor,fuel_tot=excluded.fuel_tot,gallons=excluded.gallons,miles=excluded.miles,fleet_local=excluded.fleet_local,fleet_regional=excluded.fleet_regional,truck_count=excluded.truck_count,total_hrs=excluded.total_hrs,ins_tot=excluded.ins_tot,truck_tot=excluded.truck_tot,trailer_tot=excluded.trailer_tot,truck_maint=excluded.truck_maint,trail_maint=excluded.trail_maint,storage=excluded.storage,uniforms=excluded.uniforms;`);

// OPENING fuel backfill: App.jsx FUEL is per-driver YTD, not transactions.
// Seed one statement + one synthetic fuel txn per driver dated period_end so
// per-driver totals + FUEL_TOT reconcile. Real biweekly statements append after.
L.push('\n-- fuel opening backfill (synthetic — future EFS statements are real txns)');
L.push(`insert into fdw_efs_statement(statement_id,period_start,period_end,total_amount,total_gallons) values('OPENING-${periodEnd}',${q(periodStart)},${q(periodEnd)},${num(sc.FUEL_TOT)},${num(sc.GALLONS)}) on conflict(statement_id) do update set total_amount=excluded.total_amount,total_gallons=excluded.total_gallons;`);
let fuelDrivers = 0;
for (const [name, f] of Object.entries(FUEL)) {
  if (!f || typeof f.fuel !== 'number') continue;
  fuelDrivers++;
  L.push(`insert into fdw_fuel_txn(statement_id,card_no,driver_id,txn_date,kind,gallons,amount,raw_desc) select 'OPENING-${periodEnd}','opening',id,${q(periodEnd)},'fuel',${num(f.gallons)},${num(f.fuel)},'opening backfill' from fdw_driver where name=${q(name)};`);
}

L.push('\ncommit;');
L.push(`\n-- SELF-CHECK (run after; both should return 0 rows = tie-outs pass):`);
L.push(`-- select * from (select coalesce(sum(total_cost),0) s from fdw_payroll_snapshot ps join fdw_driver d on d.id=ps.driver_id where ps.period_end='${periodEnd}' and d.kind='fleet') x, (select labor l from fdw_fleet_metrics where period_end='${periodEnd}' and entity_id='sf') y where abs(x.s-y.l)>1;`);

writeFileSync(OUT, L.join('\n') + '\n');
console.log(`Wrote ${OUT}`);
console.log(`  PERIOD=${PERIOD}  period_end=${periodEnd}`);
console.log(`  drivers=${PAYROLL.length}  fuel-mapped=${fuelDrivers}`);
console.log(`  LABOR=${sc.LABOR}  FUEL_TOT=${sc.FUEL_TOT}  MILES=${sc.MILES}`);
const payrollSum = PAYROLL.reduce((a, p) => a + (p.totalCost || 0), 0);
console.log(`  PAYROLL sum=${payrollSum.toFixed(2)}  vs LABOR=${sc.LABOR}  delta=${(payrollSum - sc.LABOR).toFixed(2)}`);
