// backfill_fdw_1b.mjs — parse src/App.jsx raw constants and emit fdw_backfill_1b.sql
// Run:  node scripts/backfill_fdw_1b.mjs
// Output: supabase/migrations/fdw_backfill_1b.sql  (run AFTER fdw_data_warehouse.sql
//         and ideally after fdw_backfill.sql, though this file is self-sufficient
//         for its own FKs — it seeds every fdw_period week-ending date it needs).
//
// Covers the "rest of the dashboard" hardcoded constants (income / office /
// contractors / agents / ATL-OTR rosters / ATL billing):
//   INCOME_2026 (weeks -> fdw_income_week, months -> fdw_income_month)
//   MONTHLY_REVENUE (2025 rows -> fdw_income_month)
//   OFFICE_W2 + WAREHOUSE -> fdw_office_payroll_snapshot
//   CONTRACTORS -> fdw_contractor_snapshot(role='contractor')
//   AGENTS      -> fdw_contractor_snapshot(role='agent')
//   ATL_WEEKLY_LOG -> fdw_op_weekly(op='atl')
//   OTR_WEEKLY_LOG -> fdw_op_weekly(op='otr')
//   ATL_BILLING -> fdw_atl_billing

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, '..', 'src', 'App.jsx');
const OUT = join(__dirname, '..', 'supabase', 'migrations', 'fdw_backfill_1b.sql');
const src = readFileSync(SRC, 'utf8');

const SNAP = '2026-07-05'; // snapshot period_end for constants that need one

// ── literal extraction (identical technique to backfill_fdw.mjs) ───────────
function extractLiteral(name) {
  const decl = new RegExp(`(?:let|const)\\s+${name}\\s*=\\s*`).exec(src);
  if (!decl) throw new Error(`literal ${name} not found`);
  let i = decl.index + decl[0].length;
  const open = src[i];
  if (open !== '[' && open !== '{') throw new Error(`${name} is not an object/array literal`);
  const close = open === '[' ? ']' : '}';
  let depth = 0, inStr = false, q = '', line = false, block = false;
  const start = i;
  for (; i < src.length; i++) {
    const c = src[i], n = src[i + 1];
    if (line) { if (c === '\n') line = false; continue; }
    if (block) { if (c === '*' && n === '/') { block = false; i++; } continue; }
    if (inStr) { if (c === '\\') { i++; continue; } if (c === q) inStr = false; continue; }
    if (c === '/' && n === '/') { line = true; i++; continue; }
    if (c === '/' && n === '*') { block = true; i++; continue; }
    if (c === '"' || c === "'" || c === '`') { inStr = true; q = c; continue; }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) { i++; break; } }
  }
  const text = src.slice(start, i);
  // eslint-disable-next-line no-eval
  return (0, eval)('(' + text + ')');
}

// ── SQL helpers ───────────────────────────────────────────────────────────
const q  = v => v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const num = v => v === null || v === undefined || Number.isNaN(v) ? 'null' : String(v);
const jb = v => v === null || v === undefined ? 'null'
  : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

// entity label -> fdw_entity id
const ENT = { SF: 'sf', 'J&A': 'ja', CE: 'ce', 'CE EAST': 'ce_east', CEEAST: 'ce_east' };
const entId = e => ENT[String(e || '').toUpperCase()] ?? null;

const MONTHNUM = { jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12 };

// ── pull values ───────────────────────────────────────────────────────────
const INCOME_2026     = extractLiteral('INCOME_2026');
const MONTHLY_REVENUE = extractLiteral('MONTHLY_REVENUE');
const OFFICE_W2       = extractLiteral('OFFICE_W2');
const WAREHOUSE       = extractLiteral('WAREHOUSE');
const CONTRACTORS     = extractLiteral('CONTRACTORS');
const AGENTS          = extractLiteral('AGENTS');
const ATL_WEEKLY_LOG  = extractLiteral('ATL_WEEKLY_LOG');
const OTR_WEEKLY_LOG  = extractLiteral('OTR_WEEKLY_LOG');
const ATL_BILLING     = extractLiteral('ATL_BILLING');

// ── derive weekly period_end dates ─────────────────────────────────────────
// Labels ("Jun 29-J5") are ambiguous. These are consecutive Sunday-ending weeks:
// first ends 2026-01-04, each subsequent +7 days. Asserted against the count.
const WEEK0 = Date.UTC(2026, 0, 4);
const weekEnd = i => new Date(WEEK0 + i * 7 * 86400000).toISOString().slice(0, 10);
const weeks = INCOME_2026.weeks;
const lastWeekEnd = weekEnd(weeks.length - 1);
if (lastWeekEnd !== SNAP) {
  throw new Error(`week-end derivation mismatch: ${weeks.length} weeks -> last=${lastWeekEnd}, expected ${SNAP}`);
}

// ── emit ──────────────────────────────────────────────────────────────────
const L = [];
L.push('-- fdw_backfill_1b.sql — generated by scripts/backfill_fdw_1b.mjs');
L.push('-- Income / office / contractors / agents / ATL-OTR rosters / ATL billing.');
L.push('-- Run AFTER fdw_data_warehouse.sql. Idempotent via ON CONFLICT upserts.');
L.push('begin;');

// -- fdw_period: seed every week-ending date fdw_income_week FKs to.
L.push('\n-- periods (seed week-ending dates so fdw_income_week FK resolves)');
for (let i = 0; i < weeks.length; i++) {
  const d = weekEnd(i);
  const cur = d === SNAP ? 'true' : 'false';
  L.push(`insert into fdw_period(period_end,period_start,is_current) values(${q(d)},'2026-01-01',${cur}) on conflict(period_end) do nothing;`);
}

// -- fdw_income_week (one row per week; cogs = rev - gp; exp/netop/other unknown per-week -> null)
L.push('\n-- income by week');
weeks.forEach((w, i) => {
  const pe = weekEnd(i);
  const cogs = (typeof w.rev === 'number' && typeof w.gp === 'number') ? +(w.rev - w.gp).toFixed(2) : null;
  L.push(`insert into fdw_income_week(period_end,label,ce,sf,di,revenue,cogs,gross_profit,carrier,total_exp,net_op_income,other_income,net_income) values(${q(pe)},${q(w.label)},${num(w.ce)},${num(w.sf)},${num(w.di)},${num(w.rev)},${num(cogs)},${num(w.gp)},${num(w.carrier)},null,null,null,${num(w.netInc)}) on conflict(period_end) do update set label=excluded.label,ce=excluded.ce,sf=excluded.sf,di=excluded.di,revenue=excluded.revenue,cogs=excluded.cogs,gross_profit=excluded.gross_profit,carrier=excluded.carrier,net_income=excluded.net_income;`);
});

// -- fdw_income_month: 2026 from INCOME_2026.months (fuller — has netInc);
//    2025 from MONTHLY_REVENUE (data INCOME_2026 doesn't carry). No overlap.
L.push('\n-- income by month (2026 from INCOME_2026.months; 2025 from MONTHLY_REVENUE)');
const seenMonth = new Set();
const months26 = INCOME_2026.months;
months26.forEach((m, i) => {
  const mn = MONTHNUM[m.m.slice(0, 3).toLowerCase()];
  const key = `2026-${String(mn).padStart(2, '0')}`;
  seenMonth.add(key);
  // partial heuristic: last entry & rev < 50% of prior month
  const isPartial = (i === months26.length - 1 && i > 0 && m.rev < months26[i - 1].rev * 0.5);
  const label = `${m.m} 26`;
  L.push(`insert into fdw_income_month(month_key,label,is_partial,ce,sf,di,revenue,gross_profit,net_income) values(${q(key)},${q(label)},${isPartial},${num(m.ce)},${num(m.sf)},${num(m.di)},${num(m.rev)},${num(m.gp)},${num(m.netInc)}) on conflict(month_key) do update set label=excluded.label,is_partial=excluded.is_partial,ce=excluded.ce,sf=excluded.sf,di=excluded.di,revenue=excluded.revenue,gross_profit=excluded.gross_profit,net_income=excluded.net_income;`);
});
let mr2025 = 0;
for (const r of MONTHLY_REVENUE) {
  const mm = r.m.match(/^(\w{3})\s+(\d{2})$/);
  if (!mm) continue;
  if (mm[2] !== '25') continue;          // 2026 handled above (fuller source)
  const mn = MONTHNUM[mm[1].toLowerCase()];
  const key = `2025-${String(mn).padStart(2, '0')}`;
  if (seenMonth.has(key)) continue;
  seenMonth.add(key);
  mr2025++;
  L.push(`insert into fdw_income_month(month_key,label,is_partial,ce,sf,di,revenue,gross_profit,net_income) values(${q(key)},${q(r.m)},false,${num(r.ce)},${num(r.sf)},${num(r.di)},${num(r.total)},${num(r.gp)},null) on conflict(month_key) do update set label=excluded.label,ce=excluded.ce,sf=excluded.sf,di=excluded.di,revenue=excluded.revenue,gross_profit=excluded.gross_profit;`);
}

// -- fdw_office_payroll_snapshot (OFFICE_W2 kind=office, WAREHOUSE kind=warehouse)
L.push('\n-- office + warehouse W-2 snapshot (period_end = ' + SNAP + ')');
const officeRow = (r, kind) => {
  const active = /former/i.test(r.note || '') ? 'false' : 'true';
  return `insert into fdw_office_payroll_snapshot(name,period_end,entity_id,kind,gross,taxes,contrib,total_cost,salary,bonus,reimb,commission,active) values(${q(r.name)},${q(SNAP)},${q(entId(r.entity))},${q(kind)},${num(r.gross)},${num(r.taxes)},${num(r.contrib)},${num(r.totalCost)},${num(r.salary)},${num(r.bonus)},${num(r.reimb)},${num(r.commission)},${active}) on conflict(name,period_end) do update set entity_id=excluded.entity_id,kind=excluded.kind,gross=excluded.gross,taxes=excluded.taxes,contrib=excluded.contrib,total_cost=excluded.total_cost,salary=excluded.salary,bonus=excluded.bonus,reimb=excluded.reimb,commission=excluded.commission,active=excluded.active;`;
};
for (const r of OFFICE_W2) L.push(officeRow(r, 'office'));
for (const r of WAREHOUSE) L.push(officeRow(r, 'warehouse'));

// -- fdw_contractor_snapshot (CONTRACTORS role=contractor, AGENTS role=agent)
L.push('\n-- contractors + agents snapshot (period_end = ' + SNAP + ')');
const contrRow = (r, role) => {
  const active = /former/i.test(r.note || '') ? 'false' : 'true';
  return `insert into fdw_contractor_snapshot(name,period_end,role,dba,weekly,weekly_total,car_total,commission,health_total,other,total,active,trust) values(${q(r.name)},${q(SNAP)},${q(role)},${q(r.dba || '')},${num(r.weekly)},${num(r.weeklyTotal)},${num(r.carTotal || 0)},${num(r.commission || 0)},${num(r.healthInsTotal || 0)},${num(r.other || 0)},${num(r.total)},${active},'high') on conflict(name,period_end) do update set role=excluded.role,dba=excluded.dba,weekly=excluded.weekly,weekly_total=excluded.weekly_total,car_total=excluded.car_total,commission=excluded.commission,health_total=excluded.health_total,other=excluded.other,total=excluded.total,active=excluded.active;`;
};
for (const r of CONTRACTORS) L.push(contrRow(r, 'contractor'));
for (const r of AGENTS)      L.push(contrRow(r, 'agent'));

// -- fdw_op_weekly (ATL + OTR per-week rosters)
L.push('\n-- ATL + OTR per-week rosters');
const opRow = (w, op) =>
  `insert into fdw_op_weekly(op,week_start,week_end,drivers,contractors,driver_pay,driver_hours,fuel_amt,fuel_gallons,contractor_pay,note,trust) values(${q(op)},${q(w.weekStart)},${q(w.weekEnd)},${jb(w.drivers || [])},${jb(w.contractors || [])},${num(w.driverPay)},${num(w.driverHours)},${num(w.fuelAmt)},${num(w.fuelGallons)},${num(w.contractorPay)},${q(w.note)},'high') on conflict(op,week_start) do update set week_end=excluded.week_end,drivers=excluded.drivers,contractors=excluded.contractors,driver_pay=excluded.driver_pay,driver_hours=excluded.driver_hours,fuel_amt=excluded.fuel_amt,fuel_gallons=excluded.fuel_gallons,contractor_pay=excluded.contractor_pay,note=excluded.note;`;
for (const w of ATL_WEEKLY_LOG) L.push(opRow(w, 'atl'));
for (const w of OTR_WEEKLY_LOG) L.push(opRow(w, 'otr'));

// -- fdw_atl_billing
L.push('\n-- ATL load-level billing (period_end = ' + SNAP + ')');
L.push(`insert into fdw_atl_billing(period_end,loads,revenue,carrier_pay,gross_profit,gross_margin,by_driver) values(${q(SNAP)},${num(ATL_BILLING.loads)},${num(ATL_BILLING.revenue)},${num(ATL_BILLING.carrierPay)},${num(ATL_BILLING.grossProfit)},${num(ATL_BILLING.grossMargin)},${jb(ATL_BILLING.byDriver || null)}) on conflict(period_end) do update set loads=excluded.loads,revenue=excluded.revenue,carrier_pay=excluded.carrier_pay,gross_profit=excluded.gross_profit,gross_margin=excluded.gross_margin,by_driver=excluded.by_driver;`);

L.push('\ncommit;');

writeFileSync(OUT, L.join('\n') + '\n');

// ── report ─────────────────────────────────────────────────────────────────
const sum = (arr, f) => arr.reduce((a, x) => a + (f(x) || 0), 0);
const officeTC = sum(OFFICE_W2, r => r.totalCost) + sum(WAREHOUSE, r => r.totalCost);
const contrTotal = sum(CONTRACTORS, r => r.total);
const agentTotal = sum(AGENTS, r => r.total);
console.log(`Wrote ${OUT}`);
console.log(`  fdw_period seeded weeks         : ${weeks.length}  (${weekEnd(0)} .. ${lastWeekEnd})`);
console.log(`  fdw_income_week rows            : ${weeks.length}`);
console.log(`  fdw_income_month rows           : ${months26.length} (2026) + ${mr2025} (2025) = ${months26.length + mr2025}`);
console.log(`  fdw_office_payroll_snapshot rows: ${OFFICE_W2.length} office + ${WAREHOUSE.length} warehouse = ${OFFICE_W2.length + WAREHOUSE.length}`);
console.log(`  fdw_contractor_snapshot rows    : ${CONTRACTORS.length} contractor + ${AGENTS.length} agent = ${CONTRACTORS.length + AGENTS.length}`);
console.log(`  fdw_op_weekly rows              : ${ATL_WEEKLY_LOG.length} atl + ${OTR_WEEKLY_LOG.length} otr = ${ATL_WEEKLY_LOG.length + OTR_WEEKLY_LOG.length}`);
console.log(`  fdw_atl_billing rows            : 1`);
console.log('  --- reconciliation ---');
console.log(`  CONTRACTORS sum(total)          : ${contrTotal.toFixed(2)}`);
console.log(`  AGENTS sum(total)               : ${agentTotal.toFixed(2)}`);
console.log(`  OFFICE_W2+WAREHOUSE sum(totalCost): ${officeTC.toFixed(2)}`);
console.log(`  INCOME_2026 weeks / months      : ${weeks.length} / ${months26.length}`);
console.log(`  ATL / OTR week counts           : ${ATL_WEEKLY_LOG.length} / ${OTR_WEEKLY_LOG.length}`);
